#pragma once

#ifndef _CRMS_JSON_SUPPORT_BASE_H_
#define _CRMS_JSON_SUPPORT_BASE_H_

#include "../../utility/nJson/DEF.h"

//#define SET NJSON_NSET
//#define GET NJSON_NGET
//#define SERIALIZE_SUPER_CLASS NJSON_NSERIALIZE_SUPER_CLASS
//#define DESERIALIZE_SUPER_CLASS NJSON_NDESERIALIZE_SUPER_CLASS

#endif //_CRMS_JSON_SUPPORT_BASE_H_
