//
// Created by nini on 10/9/17.
//

#ifndef _CRMS_RESOURCE_COMMON_AGGREGATED_NOTIFICATION_H_
#define _CRMS_RESOURCE_COMMON_AGGREGATED_NOTIFICATION_H_

#endif //_CRMS_RESOURCE_COMMON_AGGREGATED_NOTIFICATION_H_
